services:
  web:
#    build:
#      context: ./docker/web
#      dockerfile: PHP74.Dockerfile
#      dockerfile: PHP80.Dockerfile
    image: beinbm/cake:php80
#    image: php:7.4-apache-bullseye
#    image: php:8.0-apache-bullseye
#    image: registry.gitlab.com/gotphoto/platform/core/app:7.4-apache-bullseye_06-develop-
#    image: registry.gitlab.com/gotphoto/platform/core/app:8.0-apache-bullseye_13-develop
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      - ./:/var/www/html:cached
    working_dir: /var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - memcached
      - redis
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cakephp_test
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d:cached
      - dev-db-data:/var/lib/mysql
#    ports:
#      - "3306:3306"
  memcached:
    image: memcached:latest
    hostname: memcached
#    ports:
#      - "11211:11211"
  redis:
    image: "redis:latest"
    hostname: redis
#    ports:
#      - "6379:6379"
volumes:
  dev-db-data:
