services:
  web:
    image: beinbm/cake:php74 # enable for php7.4+xdebug
    #image: beinbm/cake:php80 # enable for php8.0+xdebug
#    build: # enable for own builds
#      context: ./docker/web
#      dockerfile: PHP74.Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      - ./:/var/www/html:cached
    working_dir: /var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - memcached
      - redis
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cakephp_test
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d:cached
      - dev-db-data:/var/lib/mysql
#    ports:
#      - "3306:3306"
  memcached:
    image: memcached:latest
    hostname: memcached
#    ports:
#      - "11211:11211"
  redis:
    image: "redis:latest"
    hostname: redis
#    ports:
#      - "6379:6379"
volumes:
  dev-db-data:
